name: tag beta

on:
  push:
    branches:
      - master

jobs:
  tagging:
    runs-on: ubuntu-latest

    steps:
    - name: clone and install
      run: |
        cd ${GITHUB_WORKSPACE}
        echo ${GITHUB_REPOSITORY}
        git clone https://${GITHUB_ACTOR}:${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
        cd ${GITHUB_REPOSITORY}
        npm install
    - name: test, build, deploy
      run: |
        npm run test
        npm run build
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git symbolic-ref --short HEAD
        npm run deploy:beta
